name: PF85Client-Deploy
on:
  push:
    branches:
      - master
      - 'staging/**'
      - develop
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.14.1]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install
        run: |
          npm install
      - name: Production Build
        run: |
          npm run build
      - name: Unit Tests
        run: |
          echo "Tested"
      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@v2.1.4
        env:
            SSH_PRIVATE_KEY: ${{ secrets.KEY }}
            ARGS: "-rltgoDzvO"
            SOURCE: "build/"
            REMOTE_HOST: ${{ secrets.HOST }}
            REMOTE_USER: ${{ secrets.USERNAME }}
            TARGET: ${{ secrets.REMOTE_TARGET }}
      - name: Create tarball
        run: tar -C build -czvf build.tar.gz .
      - name: Upload tarball
        uses: actions/upload-artifact@v1
        with:
          name: package.tgz
          path: build.tar.gz